name    'ccin2p3-remctl'
version '1.1.1'
source 'https://github.com/ccin2p3/puppet-ccin2p3-remctl'
author 'IN2P3 Computing Centre'
license 'CeCILL'
summary 'CC-IN2P3 remctl module'
description 'Puppet module to configure and deploy remctl server, acl and command files'
project_page 'https://github.com/ccin2p3/puppet-ccin2p3-remctl'
dependency 'puppetlabs/stdlib', '>= 4.1.0'
dependency 'puppetlabs/xinetd', '>= 1.2.0'
