name    'ccin2p3-remctl'
version '2.1.0'
source 'https://github.com/ccin2p3/puppet-remctl'
author 'IN2P3 Computing Centre'
license 'CeCILL'
summary 'CC-IN2P3 remctl module'
description 'Puppet module to configure and deploy remctl server, acl and command files'
project_page 'https://github.com/ccin2p3/puppet-remctl'
dependency 'puppetlabs/stdlib', '4.x'
dependency 'puppetlabs/xinetd', '1.x'
dependency 'puppetlabs/concat', '1.x'
